### ISSUE TITLE
managecontactslists : Unsuccessful: 404 Object not found

### ISSUE THREAD

**Issue by simlej** [mailjet/mailjet-apiv3-nodejs#110]
Hello,

I use `node-mailjet` to manage newsletter inscription like this :

```
const request = mailjet.post('contact')
      .id("email@exemple.com")
      .action('managecontactslists')
      .request({
        ContactsLists: [{
          listID: "listId",
          Action: 'addforce',
        }],
      });
return request;
```
it works fine but with some email addresses i get the error

```
trace: "Error: Unsuccessful: 404 Object not found
    at /usr/src/app/node_modules/node-mailjet/mailjet-client.js:321:23
    at Request.callback (/usr/src/app/node_modules/superagent/lib/node/index.js:728:3)
    at parser (/usr/src/app/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.res.on (/usr/src/app/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)"    
```

Can you explain me why ?

Regards,
Simon

**Comment by simlej** [comment]
Ok I found the explanation. 

You need to create the contact in mailjet before
```
mailjet.post('contact')
      .request({
        email: "email@exemple.com",
      });
```
:warning: mailjet throw an error (400 bad request) if the contact already exist.
