### ISSUE TITLE
I'm not able to post a new contact

### ISSUE THREAD

**Issue by anthonycluse** [mailjet/mailjet-apiv3-nodejs#133]
Hello,

I'm trying to post a new contact with V3 API and NodeJS but it seems not working as expected.

Error : `MJ18 A Contact resource with value "my email" for Email already exists`

However, I decided to check if the email exists on my acount but I not find "my email"....

Before executing my function with NodeJS, I have executed a curl command to check if the e-mail exist :

`curl -s \ -X GET \ --user "****:****8" \ https://api.mailjet.com/v3/REST/contact/myemail`

```
function _afterCreate(response, createdItem) {
  return mailjet.post('contact', { version: 'v3' }).request({
    IsExcludedFromCampaigns: 'true',
    Name: createdItem.compagny,
    Email: createdItem.email
  }).then((result) => {
    var contactID = result.body.Data.ID;
    return mailjet.post('contactslist', { 'version': 'v3' }).request({
      Name: 'customer'
    }).then((result) => {
      var listID = result.body.Data.ID;
      return mailjet.post('listrecipient', { 'version': 'v3' }).request({
        ContactID: contactID,
        ListID: listID
      }).then((result) => {
        console.log(result);
      }).catch((err) => {
        console.log(err);
      });
    }).catch((err) => {
      console.log(err);
    });
  }).catch((err) => {
    console.log(err);
  });
}
```

**Comment by ricky11** [comment]
did you solve this?

**Comment by scroll17** [comment]
Hey @anthonycluse 

Are you sure that you using API correctly ? 
Because i try to reproduce your error but i don't getting error.

Useful resources and links: 
- [Dev guide for Contact Management](https://dev.mailjet.com/email/guides/contact-management/)
- [Dev reference for `/contact` API endpoint](https://dev.mailjet.com/email/reference/contacts/contact/)
- [Dev reference for `/contactslist` API endpoint](https://dev.mailjet.com/email/reference/contacts/contact-list/)
- [Dev reference for Subscriptions API which includes `/listrecipient` endpoint](https://dev.mailjet.com/email/reference/contacts/subscriptions/)

In the text below i provide code examples and description for actions.

At the first step i retrieve a list of contacts: 
```javascript
const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

;(async () => {
    try {
        const request = await mailjet
            .get("contact", {'version': 'v3'})
            .request()
        
        console.dir(request.body, { depth: 10 })
    } catch (err) {
        console.log(err)
    }
})();
``` 

And then i retrieve a single _Contact_ by the email: 
```javascript
;(async () => {
    const email = 'myemail@gmail.com'

    try {
        const request = await mailjet
            .get("contact", {'version': 'v3'})
            .id(email)
            .request()
            
        console.dir(request.body, { depth: 10 })
    } catch (err) {
        console.log(err)
    }
})();
```
 
And from these both requests i was received this response: 
```
[Object: null prototype] {
  Count: 1,
  Data: [
    [Object: null prototype] {
      CreatedAt: '2022-04-13T15:59:02Z',
      DeliveredCount: 0,
      Email: 'myemail@gmail.com',
      ExclusionFromCampaignsUpdatedAt: '',
      ID: 40637617,
      IsExcludedFromCampaigns: false,
      IsOptInPending: false,
      IsSpamComplaining: false,
      LastActivityAt: '2022-04-13T15:59:02Z',
      LastUpdateAt: '2022-04-13T15:59:02Z',
      Name: '',
      UnsubscribedAt: '',
      UnsubscribedBy: ''
    }
  ],
  Total: 1
}
```

In this response you can see that email `myemail@gmail.com'` already exists in the list.

At the second step i try to create / post a new _Contact_ with the same email: 
```javascript
;(async () => {
    const email = 'myemail@gmail.com'

    try {
        const request = await mailjet
            .post('contact', { version: 'v3' })
            .request({
                IsExcludedFromCampaigns: 'true',
                Name: 'My email',
                Email: email
            })

        console.dir(request.body, { depth: 10 })
    } catch (err) {
        console.log(err)
    }
})();
```

I was receive this error response which is the same which you have: 
```
Error: Unsuccessful: Status Code: "400" Message: "MJ18 A Contact resource with value "myemail@gmail.com" for Email already exists."
    at /home/dzolo/Work/mailjet-apiv3-nodejs/mailjet-client.js:336:23
    at Request.callback (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:943:3)
    at /home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:1165:20
    at IncomingMessage.<anonymous> (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  ErrorMessage: 'MJ18 A Contact resource with value "myemail@gmail.com" for Email already exists.',
  statusCode: 400
}
```

But when i try to create new _Contact_ with other email, for example `myemail1@gmail.com`: 
```javascript
;(async () => {
    const email = 'myemail1@gmail.com'

    try {
        const request = await mailjet
            .post('contact', { version: 'v3' })
            .request({
                IsExcludedFromCampaigns: 'true',
                Name: 'My email',
                Email: email
            })

        console.dir(request.body, { depth: 10 })
    } catch (err) {
        console.log(err)
    }
})();
```

I was receive this response without any errors: 
```
[Object: null prototype] {
  Count: 1,
  Data: [
    [Object: null prototype] {
      CreatedAt: '2022-04-21T13:51:03Z',
      DeliveredCount: 0,
      Email: 'myemail1@gmail.com',
      ExclusionFromCampaignsUpdatedAt: '2022-04-21T13:51:03Z',
      ID: 47542292,
      IsExcludedFromCampaigns: true,
      IsOptInPending: false,
      IsSpamComplaining: false,
      LastActivityAt: '',
      LastUpdateAt: '',
      Name: 'My email',
      UnsubscribedAt: '',
      UnsubscribedBy: ''
    }
  ],
  Total: 1
}
```

And at the last step after these operations i again try to retrieve the list of _Contacts_  i getting this response: 
```
[Object: null prototype] {
  Count: 2,
  Data: [
    [Object: null prototype] {
      CreatedAt: '2022-04-12T16:12:47Z',
      DeliveredCount: 0,
      Email: 'myemail@gmail.com',
      ExclusionFromCampaignsUpdatedAt: '',
      ID: 39398572,
      IsExcludedFromCampaigns: false,
      IsOptInPending: false,
      IsSpamComplaining: false,
      LastActivityAt: '',
      LastUpdateAt: '',
      Name: '',
      UnsubscribedAt: '',
      UnsubscribedBy: ''
    },
    [Object: null prototype] {
      CreatedAt: '2022-04-21T13:51:03Z',
      DeliveredCount: 0,
      Email: 'myemail1@gmail.com',
      ExclusionFromCampaignsUpdatedAt: '2022-04-21T13:51:03Z',
      ID: 47542292,
      IsExcludedFromCampaigns: true,
      IsOptInPending: false,
      IsSpamComplaining: false,
      LastActivityAt: '',
      LastUpdateAt: '',
      Name: 'My email',
      UnsubscribedAt: '',
      UnsubscribedBy: ''
    }
  ],
  Total: 2
}
```

**Comment by scroll17** [comment]
This issue will be closed

**Comment by ancich** [comment]
WHY do you need to get a list of contacts?  Can I not just (literally) hard-code the recipient's email address and send an email??
