### ISSUE TITLE
Send API v3.1: 400 Type mismatch. Expected type "emailIn"

### ISSUE THREAD

**Issue by slackero** [mailjet/mailjet-apiv3-nodejs#162]
Sending the basic example with Node https://dev.mailjet.com/email/guides/send-api-v31/ results in error `400 Type mismatch. Expected type "emailIn"`.

The basic example with Send API v3 works without any problems.

**Comment by thinhtranquoc** [comment]
Same problem!

**Comment by charlypolka8** [comment]
Same ... Any idea ?

**Comment by scroll17** [comment]
Hey @slackero @thinhtranquoc @charlypolka8 

I try to reproduce your error but i can't getting error.
At the current moment on the page [Send API v3.1](https://dev.mailjet.com/email/guides/send-api-v31/) provided valid code example.
I duplicate his below: 
```javascript
const mailjet = require ('node-mailjet')
	.connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)
	
const request = mailjet
    .post("send", {'version': 'v3.1'})
    .request({
        "Messages":[
            {
                "From": {
                    "Email": "pilot@mailjet.com",
                    "Name": "Mailjet Pilot"
                },
                "To": [
                    {
                        "Email": "passenger1@mailjet.com",
                        "Name": "passenger 1"
                    }
                ],
                "Subject": "Your email flight plan!",
                "TextPart": "Dear passenger 1, welcome to Mailjet! May the delivery force be with you!",
                "HTMLPart": "<h3>Dear passenger 1, welcome to <a href=\"https://www.mailjet.com/\">Mailjet</a>!</h3><br />May the delivery force be with you!"
            }
        ]
    })

request
	.then((result) => {
		console.log(result.body)
	})
	.catch((err) => {
		console.log(err.statusCode)
	})
```

And for this code example i receive this response: 
```
[Object: null prototype] {
  Messages: [
    [Object: null prototype] {
      Status: 'success',
      CustomID: '',
      To: [
        [Object: null prototype] {
          Email: 'passenger1@mailjet.com',
          MessageUUID: 'dd79b0e9-f129-44e0-8e10-402f24338ae9',
          MessageID: '288230388105590448',
          MessageHref: 'https://api.mailjet.com/v3/REST/message/288230388105590448'
        }
      ],
      Cc: [],
      Bcc: []
    }
  ]
}
```

But i found invalid code example at this page [Code reference for SEND API v3.1](https://dev.mailjet.com/email/reference/send-emails/#v3_1_post_send).
At this page really provided invalid code example which throw the same error which you receive: 
```javascript
const mailjet = require ('node-mailjet')
    .connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)

const request = mailjet
    .post("send", {'version': 'v3.1'})
    .request({
        "SandboxMode":"true",
        "Messages":[
            {
                "From":[
                    {
                        "Email":"pilot@mailjet.com",
                        "Name":"Your Mailjet Pilot"
                    }
                ],
                "HTMLPart":"<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
                "Subject":"Your email flight plan!",
                "TextPart":"Dear passenger, welcome to Mailjet! May the delivery force be with you!",
                "To":[
                    {
                        "Email":"passenger@mailjet.com",
                        "Name":"Passenger 1"
                    }
                ]
            }
        ]
    })

request
    .then((result) => {
        console.log(result.body)
    })
    .catch((err) => {
        console.log(err.statusCode)
    })
```

This code return response: 
```
Error: Unsuccessful: 400 Type mismatch. Expected type "emailIn".
    at /home/dzolo/Work/mailjet-apiv3-nodejs/mailjet-client.js:330:23
    at Request.callback (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:943:3)
    at /home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:1165:20
    at IncomingMessage.<anonymous> (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  ErrorMessage: 'Type mismatch. Expected type "emailIn".',
  ErrorIdentifier: '418d3e8e-bfa9-4136-816d-2fe8abaa1a9f',
  statusCode: 400
}
```

But this error response not represent full error data from SEND API v3.1 and in new version `3.3.13` of the mailjet-apiv3-nodejs this problem was solved and now the code above return error response with all helpful information.
Error response provided below: 
```
Error: Unsuccessful: Status Code: "400" Message: "Type mismatch. Expected type "emailIn"."
    at /home/dzolo/Work/mailjet-apiv3-nodejs/mailjet-client.js:336:23
    at Request.callback (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:943:3)
    at /home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:1165:20
    at IncomingMessage.<anonymous> (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  ErrorMessage: 'Type mismatch. Expected type "emailIn".',
  statusCode: 400,
  ErrorIdentifier: 'b60de86d-c429-47b3-929f-e7d3f9168044',
  ErrorCode: 'mj-0004',
  ErrorRelatedTo: [ 'Messages.From' ]
}
```

And now you can see `ErrorIdentifier` which is a 128-bit universally unique identifier (UUID) for this error, `ErrorCode` which is an internal Mailjet error code for this error and `ErrorRelatedTo` which indicates which part of the payload this error.

The current `ErrorCode` `mj-0004` appears "when there is a type mismatch in the value of a property" and it really is because in request payload passed incorrect object for property `From`: 
```javascript
...
"From":[
  {
     "Email":"pilot@mailjet.com",
     "Name":"Your Mailjet Pilot"
  }
[
...
```
But the MailJet is waiting simple JS object but not array: 
```javascript
...
"From": {
     "Email":"pilot@mailjet.com",
     "Name":"Your Mailjet Pilot"
  }
...
``` 

For Send API `v3.1` you can see more detailed information about response status codes, errors and errors description at this page [Sandbox Mode](https://dev.mailjet.com/email/guides/send-api-v31/#sandbox-mode) where you need to scroll to down and then you can see table with all errors information.
