### ISSUE TITLE
Too Many Requests - Error

### ISSUE THREAD

**Issue by pcorpet** [mailjet/mailjet-apiv3-nodejs#178]
When using the mailjet library a bit intensively, Mailjet server responds with a 429 error code: `Too Many Requests`. However the lib chokes on it and fails at giving me a proper error (I had to dig a bit deep to understand what's going on):
```
Unsuccessful: null Unexpected token T in JSON at position 0
```

**Comment by scroll17** [comment]
Hey @pcorpet 

I reproduce your error repeatedly but always i get a correct error message: 
```
   Error: Unsuccessful: 429 Too Many Requests
      at /home/dzolo/Work/mailjet-apiv3-nodejs/mailjet-client.js:331:23
      at Request.callback (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:905:3)
      at IncomingMessage.<anonymous> (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:1127:20)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    ErrorMessage: 'Too Many Requests',
    ErrorIdentifier: undefined,
    statusCode: 429,
    response: <ref 1> Response {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      res: IncomingMessage { ... },
      request: Request { ... },
      req: ClientRequest { ... },
      text: '<html><body><h1>429 Too Many Requests</h1>\n' +
        'You have sent too many requests in a given amount of time.\n' +
        '</body></html>\n',
      body: {},
      files: undefined,
      buffered: true,
      headers: {
        'content-length': '117',
        'cache-control': 'no-cache',
        'content-type': 'text/html',
        connection: 'close'
      },
      header: {
        'content-length': '117',
        'cache-control': 'no-cache',
        'content-type': 'text/html',
        connection: 'close'
      },
      statusCode: 429,
      status: 429,
      statusType: 4,
      info: false,
      ok: false,
      redirect: false,
      clientError: true,
      serverError: false,
      error: Error: cannot GET /v3/REST/contactslist/13239 (429)
          at Response.toError (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/response.js:98:13)
          at ResponseBase._setStatusProperties (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/response-base.js:119:48)
          at new Response (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/response.js:44:8)
          at Request._emitResponse (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:930:18)
          at IncomingMessage.<anonymous> (/home/dzolo/Work/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:1127:42)
          at IncomingMessage.emit (node:events:539:35)
          at endReadableNT (node:internal/streams/readable:1345:12)
          at processTicksAndRejections (node:internal/process/task_queues:83:21) {
        status: 429,
        text: '<html><body><h1>429 Too Many Requests</h1>\n' +
          'You have sent too many requests in a given amount of time.\n' +
          '</body></html>\n',
        method: 'GET',
        path: '/v3/REST/contactslist/13239'
      },
      created: false,
      accepted: false,
      noContent: false,
      badRequest: false,
      unauthorized: false,
      notAcceptable: false,
      forbidden: false,
      notFound: false,
      unprocessableEntity: false,
      type: 'text/html',
      links: {},
      setEncoding: [Function: bound ],
      redirects: [],
      pipe: [Function (anonymous)],
      [Symbol(kCapture)]: false
    }
  }
```

The lib catch and handle error at `330` line in the `mailjet-client.js`: 
```
    req.end(function (err, result) {
      var body

      try {
        body = JSONb.parse(result.text)
      } catch (e) {
        body = {}
      }

      if (err) {
        const error = new Error()
        error.ErrorMessage = body.ErrorMessage || err.message
        error.ErrorIdentifier = body.ErrorIdentifier
        error.statusCode = err.status || null
        error.response = result || null
        error.message = 'Unsuccessful: ' + error.statusCode + ' ' + error.ErrorMessage
        return ret(error)
      }

      return ret(null, {
        response: result,
        body: body
      })
    })
```

And how you can see lib get `statusCode` and `ErrorMessage` from the `err` object and that mean what `err.status` had value `null` before passed to the lib.
I think it's can be error from the Mailjet server as well message `Unexpected token T in JSON at position 0` mean that was passed invalid JSON object.

If you can provide more information i can help you for solve this problem.

**Comment by scroll17** [comment]
This issue will be closed
