### ISSUE TITLE
Error on sending mails from Google Cloud Functions

### ISSUE THREAD

**Issue by IIvanov8888** [mailjet/mailjet-apiv3-nodejs#30]
Hi,
I am trying to configure mailjet on Google Cloud Functions, but I seem to always get this error:
```javascript
Error: getaddrinfo ENOTFOUND api.mailjet.com api.mailjet.com:443
    at handleError (/user_code/index.js:15:11)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/user_code/node_modules/node-mailjet/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by latanasov** [comment]
Hi @IIvanov8888, thank your for choosing Mailjet. The `Error: getaddrinfo ENOTFOUND` indicates that the remote address could not be resolved. There is not enough information for me, to investigate further. Could you maybe share your code sample? I suppose you are doing a similar request:
```
var http = require('http');
var options = {
  host: ....,
  port: .....
  path: ....
};
http.get(...)
```
PS:
The google "Spark plan" does not allow external API calls, any chance you need an upgrade ?

**Comment by IIvanov8888** [comment]
Hi, 
I thought so , I am using the Free Plan (Spark) so that must be the reason . This is the code I am using :
```javascript
const nodeMailjet = require("node-mailjet").connect('API_KEY', 'API_SECRET');

function handleError (err) {
    console.error(err);
    throw new Error(err.ErrorMessage);
}
 
function newContact (email) {
  nodeMailjet.post('contact')
      .request({Email: email})
      .catch(handleError);
}
 
function testEmail (text) {
  email = {};
  email['FromName'] = 'Your Name';
  email['FromEmail'] = 'EMAIL';
  email['Subject'] = 'Test Email';
  email['Recipients'] = [{Email: 'EMAIL'}];
  email['Text-Part'] = text;
 
  nodeMailjet.post('send')
    .request(email).then(function (result) {
    console.info(response);
    })
    .catch(handleError);
}

exports.sendMails = functions.https.onRequest((req, res) => {
    testEmail('First mail');
});
```
PS: This code works on LOCAL

**Comment by latanasov** [comment]
@IIvanov8888 yes unfortunately you'll be able to access "Google services only " on the Spark plan. You can check the "Outbound networking" field in their [plan ](https://firebase.google.com/pricing/)listing.

**Comment by IIvanov8888** [comment]
@latanasov thank you for the quick response , I am closing the issue as it is not relevant anymore
