### ISSUE TITLE
Send email with firebase functions (getaddrinfo ENOTFOUND api.mailjet.com api.mailjet.com:443)

### ISSUE THREAD

**Issue by nsantosdaveiga** [mailjet/mailjet-apiv3-nodejs#35]
Hi when I try to send an email I have this error : 

`{ Error: Unsuccessful
    at /user_code/node_modules/node-mailjet/mailjet-client.js:220:23
    at Request.callback (/user_code/node_modules/node-mailjet/node_modules/superagent/lib/node/index.js:688:3)
    at ClientRequest.<anonymous> (/user_code/node_modules/node-mailjet/node_modules/superagent/lib/node/index.js:615:10)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  ErrorMessage: 'getaddrinfo ENOTFOUND api.mailjet.com api.mailjet.com:443',
  statusCode: null,
  response: null }`

**Comment by Zhivko-Mailjet** [comment]
@nsantosdaveiga 
The error seem to be related with your hosting platform, not able to resolve the remote. Could be linked to this issue: https://github.com/mailjet/mailjet-apiv3-nodejs/issues/30

**Comment by nsantosdaveiga** [comment]
@Zhivko-Mailjet, yes I think is linked to this issue. I have a free plan and I can't do external API calls
