### ISSUE TITLE
Help with "Ouch! Something went wrong on our side and we apologize!" Error

### ISSUE THREAD

**Issue by newbreedofgeek** [mailjet/mailjet-apiv3-nodejs#51]
Hi Guys,

I've been using the MailJet v3.1 API to send status reports for our app.

We compose a basic email and attach a PDF file. The PDF file itself is not very big (649 KB) and has images. When I try and run this I get the "Ouch! Something went wrong on our side and we apologize!". The full error is here:

```
{ Error: Unsuccessful
    at /Users/markpaul/Documents/Source/Software/reporting-service/node_modules/node-mailjet/mailjet-client.js:220:23
    at Request.callback (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/index.js:718:3)
    at parser (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on.e (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at MailjetClient.httpRequest (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/node-mailjet/mailjet-client.js:200:10)
    at MailjetResource.result (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/node-mailjet/mailjet-client.js:311:17)
    at MailjetResource.request (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/node-mailjet/mailjet-client.js:384:15)
    at /Users/markpaul/Documents/Source/Software/reporting-service/actionHtmlEmailReports.js:183:14
    at next (native)
    at onFulfilled (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/co/index.js:65:19)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at next (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/co/index.js:100:51)
    at onFulfilled (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/co/index.js:69:7)
    at /Users/markpaul/Documents/Source/Software/reporting-service/node_modules/co/index.js:54:5
    at co (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/co/index.js:50:10)
    at Object.module.exports.handler (/Users/markpaul/Documents/Source/Software/reporting-service/actionHtmlEmailReports.js:51:3)
    at [eval]:1:40
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:354:27)
    at run (bootstrap_node.js:123:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:122:9)
    at bootstrap_node.js:505:3
  ErrorMessage: 'Ouch! Something went wrong on our side and we apologize! Please contact our support team who’ll be able to help you on this',
  statusCode: 500,
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{"ErrorIdentifier":"e777ae92-621b-440e-91f5-b37ed5341719","StatusCode":500,"ErrorMessage":"Ouch! Something went wrong on our side and we apologize! Please contact our support team who’ll be able to help you on this"}',
        read: [Function] },
     request: 
      Request {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'POST',
        url: 'https://api.mailjet.com/v3.1/send',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        _query: [],
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _data: [Object],
        req: [Object],
        protocol: 'https:',
        host: 'api.mailjet.com',
        _endCalled: true,
        _callback: [Function],
        res: [Object],
        response: [Circular],
        called: true },
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 866406,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /v3.1/send HTTP/1.1\r\nHost: api.mailjet.com\r\nAccept-Encoding: gzip, deflate\r\nuser-agent: mailjet-api-v3-nodejs/3.2.1\r\nContent-type: application/json\r\nAuthorization: Basic codehereremovedforgithub=\r\nContent-Length: 866406\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/v3.1/send',
        _ended: true,
        parser: null,
        res: [Object] },
     text: '{"ErrorIdentifier":"e777ae92-621b-440e-91f5-b37ed5341719","StatusCode":500,"ErrorMessage":"Ouch! Something went wrong on our side and we apologize! Please contact our support team who’ll be able to help you on this"}',
     body: 
      { ErrorIdentifier: 'e777ae92-621b-440e-91f5-b37ed5341719',
        StatusCode: 500,
        ErrorMessage: 'Ouch! Something went wrong on our side and we apologize! Please contact our support team who’ll be able to help you on this' },
     files: undefined,
     buffered: true,
     headers: 
      { 'content-length': '218',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Tue, 13 Mar 2018 04:00:04 GMT',
        connection: 'close' },
     header: 
      { 'content-length': '218',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Tue, 13 Mar 2018 04:00:04 GMT',
        connection: 'close' },
     statusCode: 500,
     status: 500,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error: 
      { Error: cannot POST /v3.1/send (500)
          at Response.toError (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/response.js:94:15)
          at ResponseBase._setStatusProperties (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/response-base.js:123:16)
          at new Response (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/response.js:41:8)
          at Request._emitResponse (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/index.js:742:20)
          at parser (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/index.js:906:38)
          at IncomingMessage.res.on.e (/Users/markpaul/Documents/Source/Software/reporting-service/node_modules/superagent/lib/node/parsers/json.js:19:7)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:80:11)
          at process._tickDomainCallback (internal/process/next_tick.js:128:9)
        status: 500,
        text: '{"ErrorIdentifier":"e777ae92-621b-440e-91f5-b37ed5341719","StatusCode":500,"ErrorMessage":"Ouch! Something went wrong on our side and we apologize! Please contact our support team who’ll be able to help you on this"}',
        method: 'POST',
        path: '/v3.1/send' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     type: 'application/json',
     charset: 'UTF-8',
     links: {},
     setEncoding: [Function: bound ],
     redirects: [] } }

```

I use the send email code as per here: https://dev.mailjet.com/guides/#sending-with-attached-files

Specific method:
```
const request = mailjet
            .post("send", {'version': 'v3.1'})
            .request({
                "Messages":[{
                  "From": {
                    "Email": "from",
                    "Name": "Mark"
                  },
                  "To": [{
                      "Email": toEmail,
                      "Name": `${user.firstName} ${user.lastName}`
                    }],
                  "Subject": `${user.firstName}, here is your Program Report`,
                  "HTMLPart": htmlEmailTemplate(user, program),
                  "Attachments": [ {
                    "ContentType": "application/pdf",
                    "Filename": `${user.firstName}_${user.lastName}_${reportId}.pdf`,
                    "Base64Content": pdfFile.toString('base64')
                  }]
                }]
            });
```

The PDF is not corrupted as when i write to file it is fine.

I have another email report that gets sent out, also with a PDF which is smaller (35 KB) as there are no images - but this works fine.

Any idea what is wrong?

Thanks,
Mark

**Comment by philiiiiiipp** [comment]
I have seen this happening as well. I resend those emails and it seems to work afterwards. I think they are at their capacity or so.

**Comment by mskochev** [comment]
Hi guys, this issue happens when Mailjet couldn't handle the request in a timely manner. In this case the best option is to retry. This is not a problem related to the wrapper itself.
