### ISSUE TITLE
superagent: double callback bug

### ISSUE THREAD

**Issue by philiiiiiipp** [mailjet/mailjet-apiv3-nodejs#54]
I see some error logs coming from mailjet. What is going on there?

```
superagent: double callback bug
{ Error: Unsuccessful
    at /srv/www/node_modules/node-mailjet/mailjet-client.js:220:23
    at Request.callback (/srv/www/node_modules/superagent/lib/node/index.js:718:3)
    at ClientRequest.req.once.err (/srv/www/node_modules/superagent/lib/node/index.js:646:10)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:467:13)
    at TLSSocket.Socket._destroy (net.js:508:3)
    at WriteWrap.afterWrite (net.js:802:10) ErrorMessage: 'write EPIPE', statusCode: null, response: null }
```

**Comment by todorDim** [comment]
Hello @philiiiiiipp ,

Do you still have those error messages ? 

Regards,
T.

**Comment by philiiiiiipp** [comment]
No it works fine at the moment. So I suppose this can be closed.
