### ISSUE TITLE
Unsuccessful Error

### ISSUE THREAD

**Issue by Panoplos** [mailjet/mailjet-apiv3-nodejs#55]
Hello, just trying to test the API in our app, and I am not able to successfully send any emails. Using the following code:

```
import mailer from 'server/store/site/mailer'
const mailjet = Mailjet.connect(env('MAILJET_KEY'), env('MAILJET_SECRET'))

export async function sendConfirmationEmail(account, confirmationCode, locale) {
        let link = `${env('PROXY_PROTO')}://${env('PROXY_HOST')}${env('PROXY_PORT').length > 0 ? `:${env('PROXY_PORT')}` : ''}/registration?`
        link += `code=${confirmationCode}`
        link = encodeURI(link)
        return mailjet.post('send').request({
                Messages :[
                        {
                                From: {
                                        Email: "XXXXXX@XXXXXX",
                                        Name: "XXXXXX"
                                },
                                To: [
                                        {
                                                "Email": account.email,
                                                "Name": "New User"
                                        }
                                ],
                                TemplateID: 361710,
                                TemplateLanguage: true,
                                Subject: "XXXXX Registration Confirmation",
                                Variables: {
                                        confirmation_link: link
                                }
                        }
                ]
        })
}
```

I am getting the following error:

```bash
Error
Unsuccessful
Error: Unsuccessful
    at /home/ubuntu/registration-referral/node_modules/node-mailjet/mailjet-client.js:220:23
    at Request.callback (/home/ubuntu/registration-referral/node_modules/superagent/lib/node/index.js:718:3)
    at IncomingMessage.parser (/home/ubuntu/registration-referral/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
From previous event:
    at MailjetClient.httpRequest (/home/ubuntu/registration-referral/node_modules/node-mailjet/mailjet-client.js:200:10)
    at MailjetResource.result (/home/ubuntu/registration-referral/node_modules/node-mailjet/mailjet-client.js:311:17)
    at MailjetResource.request (/home/ubuntu/registration-referral/node_modules/node-mailjet/mailjet-client.js:384:15)
    at _callee2$ (/home/ubuntu/registration-referral/src/server/mailer/index.js:56:30)
    at tryCatch (/home/ubuntu/registration-referral/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/ubuntu/registration-referral/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/registration-referral/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/ubuntu/registration-referral/src/server/mailer/index.js:132:993)
    at /home/ubuntu/registration-referral/src/server/mailer/index.js:132:1223
    at new Promise (<anonymous>)
    at /home/ubuntu/registration-referral/src/server/mailer/index.js:132:904
    at sendConfirmationEmail (/home/ubuntu/registration-referral/src/server/mailer/index.js:73:177)
    at Object._callee2$ (/home/ubuntu/registration-referral/src/server/koa/auth/index.js:143:4)
    at tryCatch (/home/ubuntu/registration-referral/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/ubuntu/registration-referral/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/registration-referral/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/ubuntu/registration-referral/src/server/koa/auth/index.js:511:1601)
    at /home/ubuntu/registration-referral/src/server/koa/auth/index.js:511:1761
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
---------------------------------------
```

**Comment by Panoplos** [comment]
OK, figured out that I needed to add the api version 'v3.1' to the config. This was a little confusing in the README, as the example has v3.1 set, but then goes on to use v3 api calls. I recommend this is changed.

**Comment by iyobo** [comment]
Maljet's API lacks basic error handling in general. 
Good luck using them. See https://github.com/mailjet/mailjet-apiv3-nodejs/issues/57
