### ISSUE TITLE
Unable to bundle your SDK with webpack

### ISSUE THREAD

**Issue by Maxou44** [mailjet/mailjet-apiv3-nodejs#92]
Hello, you are using dynamic import, so we can't bundle your SDK in a standalone app with webpack

```TypeError: require is not a function
    at Object.<anonymous> (/app/index.js:59206:14)
    at __webpack_require__ (/app/index.js:20:30)
    at Object.<anonymous> (/app/index.js:59195:20)
    at __webpack_require__ (/app/index.js:20:30)
    at Object.<anonymous> (/app/index.js:18732:20)
    at __webpack_require__ (/app/index.js:20:30)
    at Object.<anonymous> (/app/index.js:58131:17)
    at __webpack_require__ (/app/index.js:20:30)
    at Object.<anonymous> (/app/index.js:33303:15)
    at __webpack_require__ (/app/index.js:20:30)```
```

At bundled line : 
```var crypto = require('crypto');```

**Comment by acestudiooleg** [comment]
@Maxou44  Can you provide webpack config, please?

**Comment by javierguzman** [comment]
@Maxou44  Bonjour! Did you manage to resolve this? I am getting exactly the same problem. It is strange because locally it seems ok even within Docker. However when I deploy on Google Cloud it just fails, only if I do not use node-mailjet then it works all ok.

**Comment by Maxou44** [comment]
I removed the SDK and used the API with node-fetch ;)

**Comment by javierguzman** [comment]
@Maxou44 That is sad...I guess I will have to do the same as I do not see much activity around here. Maybe even change provider now I am not that locked. Thank you very much for the quick answer!!

**Comment by kevinmiguet** [comment]
I removed mailjet and switched to sendinblue. Sorry guys :'(
